"""
6.5
--- 
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
https://projecteuler.net/problem=2
"""

def fib_generator(number1,number2):
	fib = [number1,number2]
	for i in range(1,10):
		result = number1 + number2
		number1, number2 = number2, result
		fib.append(result)
		if len(fib) == 10:
			break
	return fib

print(fib_generator(5,0))
#print(a)